const Map<String, Map<String, String>> languages = {
  "tr": tr,
  "en": en
};

const Map<String, String> tr = {
  "settings" : "Ayarlar",
  "store" : "Mağazalar",
  "home" : "Ana Sayfa",
  "wallet" : "QR",
  "payment" : "Ödeme",
  "menu" : "Menü/Sipariş",
  "hello" : "Merhaba",
  "join_now" : "Şimdi Katıl",
  "berry_cake" : "Berry İmzası",
  "cake_strawberry" : "Kırmızı Düşler",
  "creme_brule" : "Karamel Kabuğu",
  "cup_berry" : "Berry Kasesi",
  "eclair" : "Çikolata Şöleni",
  "pie_apple" : "Anne Usulü Elmalı",
  "pie_berry" : "Berry Turta",
  "roll_strawberry" : "Çilek Sarması",
  "souffle" : "Akışkan Çikolata",
  "waffle" : "Meyve Bahçesi Waffle",
  "berry_cake_description": "Özel krema katmanları arasında taze orman meyveleriyle hazırlanan, hafif ve ferahlatıcı Berry imzalı pasta.",
  "cake_strawberry_description": "Yumuşacık pandispanya, gerçek çilek dilimleri ve ipeksi pastacı kremasının buluştuğu bir klasik.",
  "creme_brule_description": "Vanilya çubuklarıyla aromalandırılmış pürüzsüz krema ve üzerinde altın sarısı, çıtır karamelize şeker tabakası.",
  "cup_berry_description": "Kat kat bisküvi kırıntıları, hafif krema ve yoğun meyve sosuyla servis edilen pratik lezzet kupası.",
  "eclair_description": "İçi bol vanilyalı krema dolgulu, üzeri Belçika çikolatasıyla kaplanmış çıtır Fransız hamuru.",
  "pie_apple_description": "Tarçınla harmanlanmış karamelize elmalar ve kıyır kıyır hamuruyla tam bir ev yapımı sıcaklığı.",
  "pie_berry_description": "Yaban mersini ve frambuazın mayhoş tadını çıtır tart hamuruyla birleştiren meyve tutkunlarına özel tarif.",
  "roll_strawberry_description": "Özenle sarılmış hafif kek rulosu içerisinde taze çilekler ve yoğun krema dolgusu.",
  "souffle_description": "Berry Coffee farkıyla; merkezinden yoğun ve sıcak çikolata akan, anlık hazırlanan efsanevi sufle.",
  "waffle_description": "Dışı çıtır, içi yumuşak waffle hamuru üzerine seçeceğiniz meyveler ve eritilmiş çikolata sosuyla.",
  "did_you_try_these" : "Tatlıları denedin mi?",
  "did_you_try_breakfasts" : "Kahvaltıları denedin mi?",
  "all" : "Tümü",
  "blueberry_pancake": "Mavi Düşler Pankek",
  "eggs_strawberry_yogurt_pastry": "Berry Kahvaltı Şöleni",
  "eggs_avocados": "Yeşil Güç Tabağı",
  "eggs_croissant_berries": "Kruvazan Esintisi",
  "eggs_fruits_tomato": "Gökkuşağı Brunch",
  "eggs_mushrooms_avocado": "Orman Lezzetleri Tabağı",
  "honey_butter_pancake": "Altın Petek Pankek",
  "sandwich_avocados": "Avokado Bahçesi Sandviç",
  "strawberry_pancake": "Kırmızı Neşe Pankek",
  "toasted_bread_butter_fruits": "Çıtır Meyve Keyfi",
  "blueberry_pancake_description": "Taze yaban mersini taneleriyle pişirilmiş, üzerine akçaağaç şurubu gezdirilen pofuduk pankek katları.",
  "eggs_strawberry_yogurt_pastry_description": "Çilekli yoğurt, taze meyveler ve çıtır hamur işi eşliğinde sunulan protein dolu Berry tabağı.",
  "eggs_avocados_description": "Tam kıvamında pişmiş yumurtalar, taze avokado dilimleri ve özel baharat karışımıyla sağlıklı bir başlangıç.",
  "eggs_croissant_berries_description": "Tereyağlı çıtır kruvazan arasında servis edilen yumurtalar ve yanında taze orman meyveleri.",
  "eggs_fruits_tomato_description": "Çeri domateslerin tazeliği, mevsim meyveleri ve yumurtanın uyumuyla hafif ve dengeli bir tabak.",
  "eggs_mushrooms_avocado_description": "Sotelenmiş kültür mantarı, kremsi avokado ve yumurtanın buluştuğu doyurucu ve gurme bir kahvaltı.",
  "honey_butter_pancake_description": "Gerçek yayık tereyağı ve süzme çiçek balı ile servis edilen, ağızda dağılan klasik pankek lezzeti.",
  "sandwich_avocados_description": "Ekşi mayalı ekmek arasında ezilmiş avokado, özel soslar ve taze yeşilliklerle hazırlanan doyurucu sandviç.",
  "strawberry_pancake_description": "Taze çilek dilimleri, hafif krema ve Berry Coffee’nin özel şurubuyla tatlandırılmış pankek kulesi.",
  "toasted_bread_butter_fruits_description": "Kızarmış çıtır ekmek dilimleri üzerine sürülen taze tereyağına eşlik eden renkli meyve şöleni.",
  "blueberry_cool_lime": "Yaban Mersini Ferahlığı",
  "chocolate_chips_berry_frappuccino": "Berry-Choc Parçacıklı",
  "chocolate_frappuccino": "Yoğun Belçika Soğuğu",
  "frappuccino": "Klasik Berry Frappe",
  "green_tea_frappuccino": "Yeşil Çay Harmanı",
  "peach_milkshake": "Şeftali Bulutu Milkshake",
  "pistachio_chocolate_shake": "Antep Rüyası Shake",
  "pistachio_frappuccino": "Fıstıklı Serinlik",
  "strawberry_churro_frappuccino": "Çilekli Churro Keyfi",
  "strawberry_red_velvet_mocha": "Kadife Çilek Mocha",
  "blueberry_cool_lime_description": "Taze misket limonu ve yaban mersini tanelerinin buzlu ferahlatıcı buluşması.",
  "chocolate_chips_berry_frappuccino_description": "Berry meyveleri ve çıtır çikolata parçacıklarının kremsi, buzlu uyumu.",
  "chocolate_frappuccino_description": "Zengin çikolata sosu ve taze sütün buzla harmanlandığı klasik bir tatlı mola.",
  "frappuccino_description": "Özel kavrulmuş kahve çekirdeklerimizin kremsi dokuyla birleştiği imza soğuk lezzet.",
  "green_tea_frappuccino_description": "Premium Matcha yeşil çayı ve sütle hazırlanan, egzotik ve ferahlatıcı bir deneyim.",
  "peach_milkshake_description": "Gerçek şeftali parçaları ve yoğun vanilyalı dondurmanın ipeksi karışımı.",
  "pistachio_chocolate_shake_description": "Gerçek Antep fıstığı ezmesi ve bitter çikolatanın yoğun kıvamlı shake hali.",
  "pistachio_frappuccino_description": "Fıstık aroması ve kahvenin buzlu sütle buluştuğu gurme bir soğuk içecek.",
  "strawberry_churro_frappuccino_description": "Tarçınlı churro lezzeti ve taze çilek sosunun sıra dışı, tatlı birleşimi.",
  "strawberry_red_velvet_mocha_description": "Kırmızı kadife keki aroması, taze çilekler ve beyaz çikolatalı mochanın eşsiz dansı.",
  "for_you" : "Senin için",
  "menu2" : "Menü",
  "my_orders" : "Siparişlerim",
  "my_favorite" : "Favorilerim",
  "drinks" : "İçecekler",
  "cakes" : "Tatlılar",
  "breakfasts" : "Kahvaltı",
  "bakery" : "Fırın",
  "new_code" : "Yeni Kod Üret",
  "add_money" : "PARA YÜKLE",
  "for_every_drink" : "Her içecekte",
  "earn" : "kazan",
  "add_product" : "Sepete Ekle",
  "my_cart" : "Sepetim",
  "confirm" : "Onayla",
  "insufficient_balance" : "Bakiyen henüz yeterli değil",
  "add_funds_to_wallet" : "Devam etmek için cüzdanına küçük bir takviye yapabilirsin",
  "order_creation_failed" : "Sipariş oluşturulurken bir hata oluştu",
  "your_order" : "Siparişin",
  "success_creating_order" : "Siparişiniz alındı. Siparişlerim bölümünden sipariş durumunu takip edebilirsiniz.",


  "want_to_sign_up" : "Hesap oluşturmak ister misin?",
  "go_home" : "Ana Menüye Git",
  "success_adding_in_basket" : "Ürün sepete eklendi",
  "error_creating_order" : "Sipariş verilirken bir hata oluştu.",
  "no_product_found" : "Ürün bulunamadı",
  "switch_theme" : "Tema Değiştir",
  "saved_cards" : "Kayıtlı Kartlar",
  "basket" : "Sepet",
  "order" : "Sipariş Ver",
  "latte_description" : "Latte, espresso ve buharda pişirilmiş süt ile hazırlanan bir kahve içeceğidir. Genellikle az miktarda köpükle süslenir.",
  "americano_description" : "Amerikano, espresso'nun sıcak suyla seyreltilmesiyle hazırlanan bir kahve içeceğidir ve damla kahveye benzer bir güce sahiptir ancak farklı bir lezzet profiline sahiptir.",
  "mocha_description" : "Mocha, çikolata aromalı bir latté'dir. Genellikle espresso, buharda pişirilmiş süt, çikolata şurubu ve krem şanti ile yapılır.",
  "espresso_description" : "Espresso, ince öğütülmüş kahveden yüksek basınç altında sıcak su geçirilerek demlenen konsantre bir kahve türüdür.",
  "welcome" : "Hoşgeldin",
  "all_products" : "Tüm Ürünler",
  "most_popular" : "En Popüler Kahveler",
  "latte" : "Latte" ,
  "americano" : "Americano" ,
  "mocha" : "Mocha",
  "espresso" : "Espresso",
  "coffee" : "Kahve",
  "tea" : "Çay",
  "food" : "Yiyecek",
  "the_best_int_town" : "Şehrinin En iyisi",
  "profile_view" : "Profil",
  "shop_view" : "Mağaza",
  "card_view" : "Sepet",
  "show" : "Görüntüle",
  "offer_accepted_load_title": "yükü için teklifiniz kabul edildi",
  "offer_accepted_truck_title": "aracı için teklifiniz kabul edildi",
  "offer_accepted_body": "Teklifiniz kabul edildi.",
  "new_offer_load_body": "Yükünüz için yeni bir teklif geldi",
  "new_offer_truck_body": "Aracınız için yeni bir teklif geldi",
  "new_offer_load_title": "yükü için yeni bir teklif geldi",
  "new_offer_truck_title": "aracı için yeni bir teklif geldi",
  "shipment_canceled_body": "Nakliyat iptal edildi",
  "shipment_completed_body": "Nakliyat tamamlandı!",
  "new_message_title": "sana yeni bir mesaj gönderdi",
  "anonymous_login": "Misafir Olarak Devam Et",
  "pick_load": "Yük Seç",
  "truck_post_details": "Araç İlan Detayları",
  "propose": "Teklif",
  "update_shipment_state": "Nakliyat Durumunu Güncelle",
  "load_received": "Yük Alındı",
  "target_reached": "Hedefe Ulaşıldı",
  "load_delivered": "Yük Teslim Edildi",
  "load_owner": "Yük Sahibi",
  "this_shipment_is_canceled": "Bu nakliyat iptal edildi!",
  "this_shipment_is_completed": "Bu nakliyat tamamlandı.",
  "complete": "Bitir",
  "error_cancel_shipment": "Nakliyat iptal edilirken bir hata oluştu!",
  "success_cancel_shipment": "Nakliyat başarıyla iptal edildi.",
  "details": "Detaylar",
  "state": "Durum",
  "load": "Yükü",
  "oftruck": "Aracı İle",
  "start": "Nakliyat Başladı",
  "accepted": "Kabul Edildi",
  "shipment_details": "Nakliyat Detayları",
  "active_shipments": "Aktif Nakliyatlar",
  "success_creating_shipment": "Nakliyat başarıyla oluşturuldu.",
  "error_creating_shipment": "Nakliyat onaylanırken bir hata oluştu!",
  "you_have_accepted_this_offer": "Bu teklifi kabul ettiniz!",
  "you_have_rejected_this_offer": "Bu teklifi red ettiniz!",
  "sent": "Teklif gönderildi",
  "offers": "Teklifler",
  "show_offers": "Teklifleri Görüntüle",
  "now": "Şimdi",
  "chat": "Mesaj",
  "no_offer_found": "Herhangi bir teklif bulunamadı",
  "no_shipment_found": "Nakliyat görüntülenemiyor.",
  "who_sent": "Teklifi Gönderen",
  "reject": "Reddet",
  "success_accept_offer": "Teklif kabul edildi.",
  "error_accept_offer": "Teklif kabul edilemedi. Bilinmeyen bir hata oluştu.",
  "success_reject_offer": "Teklif reddedildi.",
  "error_reject_offer": "Teklif reddedilemedi. Bilinmeyen bir hata oluştu.",
  "no_places_found": "Herhangi bir mekan bulunamadı.",
  "loading": "Yükleniyor...",
  "send_a_message": "Mesaj Gönder",
  "no_chats_found": "Herhangi bir mesaj bulunmadı.",
  "error_creating_chat": "Mesajlarda bir sorun oluştu!",
  "error_creating_offer": "Teklif gönderirken bir sorun oluştu!",
  "success_creating_offer": "Teklif başarıyla gönderildi.",
  "offer_details": "Teklif Detayları",
  "chats": "Mesajlar",
  "show_results": "Sonuçları Göster",
  "hide_results": "Sonuçları Gizle",
  "pick_truck": "Araç seç",
  "user_name": "İletişim Adı",
  "user_details": "İletişim Detayları",
  "upload": "Yükle",
  "view": "Görüntüle",
  "email": "Email",
  "phone": "Telefon",
  "password": "Şifre",
  "password_again": "Şifre Tekrar",
  "forgot_password": "Şifremi Unuttum",
  "login": "Giriş Yap",
  "or": "ya da",
  "user_agreement": " Kullanıcı Sözleşmesi",
  "by_continuing": "Devam ederek",
  "accepted_user_agreement": "'ni kabul etmiş olacaksınız.",
  "sign_up": "Kayıt Ol",
  "kruvasan": "Kruvasan",
  "berry_cup_cilekli": "Berry Cup Çilekli",
  "berry_cup_krokanli": "Berry Cup Krokanlı",
  "berry_cup_lotuslu": "Berry Cup Lotuslu",
  "berry_cup_oreolu": "Berry Cup Oreolu",
  "berry_pavlova": "Berry Pavlova",
  "bitter_cikolatali_pasta": "Bitter Çikolatalı Pasta",
  "brownie": "Brownie",
  "cheesecake_cilek": "Cheesecake Çilek",
  "cheesecake_frambuaz": "Cheesecake Frambuaz",
  "cheesecake_yabanmersini": "Cheesecake Yabanmersini",
  "chocolate_blueberry": "Chocolate Blueberry",
  "cookie_caramel": "Cookie Caramel",
  "cookie_chocolate": "Cookie Chocolate",
  "crunberry": "Crunberry",
  "cilek_raspberry": "Çilek Raspberry",
  "cilekli_tart": "Çilekli Tart",
  "dubai_cikolatasi_pasta": "Dubai Çikolatası Pasta",
  "dubai_cikolatasi": "Dubai Çikolatası",
  "dubai_san_sebastian": "Dubai San Sebastian",
  "findik_tart": "Fındık Tart",
  "fistik_ekler": "Fıstık Ekler",
  "fistik_krokan": "Fıstik Krokan",
  "fistik_ruyasi": "Fıstık Rüyası",
  "havuc_dilimi": "Havuç Dilimi",
  "kremali_cilek_kruvasan": "Kremalı Çilek Kruvasan",
  "lampos": "Lampos",
  "love_berry_beyaz": "Love Berry Beyaz",
  "love_berry_klasik": "Love Berry Klasik",
  "love_berry_sutlu": "Love Berry Sütlü",
  "roll_tart": "Roll Tart",
  "royal_dubai": "Royal Dubai",
  "sade_kruvasan": "Sade Kruvasan",
  "san_sebastian": "San Sebastian",
  "snickers": "Snickers",
  "tiramisu": "Tiramisu",
  "kruvasan_description": "Tereyağının eşsiz kokusuyla kat kat açılmış, dışı çıtır içi yumuşacık klasik Fransız lezzeti.",
  "berry_cup_cilekli_description": "Taze çilek katmanları, hafif krema ve yumuşak pandispanya ile bardakta sunulan ferah bir lezzet.",
  "berry_cup_krokanli_description": "Çıtır fındık krokan parçaları ve ipeksi kremanın bardaktaki muhteşem doku uyumu.",
  "berry_cup_lotuslu_description": "Meşhur Lotus Biscoff bisküvisi ve karamelize bisküvi ezmesiyle hazırlanan modern bir tatlı.",
  "berry_cup_oreolu_description": "Yoğun kakaolu Oreo bisküvi parçaları ve hafif kremanın bir araya geldiği vazgeçilmez lezzet.",
  "berry_pavlova_description": "Dışı çıtır, içi yumuşak beze tabanı üzerinde taze orman meyveleri ve hafif krema dolgusu.",
  "bitter_cikolatali_pasta_description": "Yüksek kaliteli bitter çikolata ve nemli kek katmanlarıyla çikolata tutkunlarına özel bir deneyim.",
  "brownie_description": "Yoğun çikolata dolgulu, dışı hafif kabuklu ve içi nemli gerçek ev yapımı brownie lezzeti.",
  "cheesecake_cilek_description": "Kıvamlı peynir dolgusu üzerinde taze çileklerden hazırlanan parlak ve tatlı sos.",
  "cheesecake_frambuaz_description": "Frambuazın kendine has mayhoşluğu ile dengelenmiş, pürüzsüz dokulu klasik cheesecake.",
  "cheesecake_yabanmersini_description": "Taze yaban mersini taneleri ve özel meyve sosuyla taçlandırılmış kremsi cheesecake.",
  "chocolate_blueberry_description": "Premium çikolata seçkisi ve berry dokunuşlarıyla hazırlanan çok katmanlı özel pasta.",
  "cookie_caramel_description": "Dışı kıtır, içi yumuşak; her ısırıkta akan akışkan karamel dolgulu gurme kurabiye.",
  "cookie_chocolate_description": "Bol çikolata parçacıklarıyla dolu, ağızda dağılan klasik bir kurabiye keyfi.",
  "crunberry_description": "Çıtır taban üzerinde taze meyve asiditesinin ve kremanın dengeli buluşması.",
  "cilek_raspberry_description": "Çilek ve ahududunun muhteşem uyumunu barındıran, taze meyve aromalı hafif tatlı.",
  "cilekli_tart_description": "Gevrek tart hamuru içerisinde hafif pastacı kreması ve bolca taze çilek dilimleri.",
  "dubai_cikolatasi_pasta_description": "Çıtır kadayıf, Antep fıstığı ezmesi ve çikolatanın ikonik uyumunun pasta formu.",
  "dubai_cikolatasi_description": "Dünyayı kasıp kavuran akışkan fıstık kremalı ve çıtır kadayıf dolgulu el yapımı çikolata.",
  "dubai_san_sebastian_description": "Yanık dış yüzeyi ve kremsi iç dokusuyla San Sebastian'ın Dubai çikolatasıyla birleştiği lüks dokunuş.",
  "findik_tart_description": "Kavrulmuş fındıkların aromasıyla zenginleşen, gevrek tabanlı ve yoğun fındıklı tart.",
  "fistik_ekler_description": "İnce hamurlu ekler içerisinde yoğun Antep fıstıklı krema ve fıstık parçalı kaplama.",
  "fistik_krokan_description": "Karamelize edilmiş fıstık parçaları ve yumuşak kremanın birleştiği çıtır bir lezzet şöleni.",
  "fistik_ruyasi_description": "Tamamen Antep fıstığı odaklı, yeşilin en lezzetli halini sunan yumuşacık bir pasta.",
  "havuc_dilimi_description": "Bol fıstıklı, incecik hamur katmanlarından oluşan ve arasına kaymak yakışan geleneksel şerbetli lezzet.",
  "kremali_cilek_kruvasan_description": "Arasına taze çırpılmış krema ve dilimlenmiş çilekler eklenerek zenginleştirilmiş dev kruvasan.",
  "lampos_description": "Özel dolgusu ve karakteristik sunumuyla damakta iz bırakan imza pastalarımızdan.",
  "love_berry_beyaz_description": "Beyaz çikolatanın zarif tadıyla kaplanmış, sevgiyle hazırlanan taze meyveli tatlı.",
  "love_berry_klasik_description": "Klasik bitter çikolata ve orman meyvelerinin romantik ve dengeli buluşması.",
  "love_berry_sutlu_description": "Sütlü çikolatanın yumuşak içimiyle hazırlanan, meyve dolgulu tatlı bir mola.",
  "roll_tart_description": "Hafif sünger keki ve meyveli iç dolgusuyla rulo şeklinde hazırlanan nostaljik bir lezzet.",
  "royal_dubai_description": "Altın sarısı fıstık ezmesi ve en kaliteli çikolatalarla hazırlanan krallara layık bir tatlı.",
  "sade_kruvasan_description": "Katmanları tek tek sayılabilen, tereyağlı ve çıtır dokulu geleneksel boş kruvasan.",
  "san_sebastian_description": "İspanya'nın meşhur yanık cheesecake'i; akışkan merkezi ve isli üst katmanıyla benzersiz.",
  "snickers_description": "Yer fıstığı, karamel ve çikolatanın meşhur uyumunu sunan katmanlı ve doyurucu pasta.",
  "tiramisu_description": "Espresso ile ıslatılmış kedidili bisküvileri ve gerçek maskarpon peynirli hafif krema.",
  "problem_signing_up": "Kayıt olurken bir hata oluştu!",
  "complete_order" : "Siparişi Tamamla",
  
  "already_have_account": "Zaten hesabım var",
  "no_account": "Hesabım yok",
  "add_photo": "Fotoğraf ekle",
  "name": "İsim",
  "surname": "Soyisim",
  "continue": "Devam Et",
  "input_email": "Email adresinizi giriniz.",
  "input_password": "Şifrenizi giriniz.",
  "input_password_again": "Şifrenizi tekrar giriniz.",
  "input_phone": "Telefon numaranızı giriniz.",
  "input_name": "İsminizi giriniz.",
  "input_surname": "Soyisminizi giriniz.",
  "upload_necessary_files": "Gerekli Dosyaları Yükleyiniz",
  "fill_out": "Bilgilerinizi Giriniz",
  "search": "Arama Yap",
  "save": "Kaydet",
  "enter_description": "Bir açıklama yazınız",
  "description": "Açıklama",
  "start_date": "Başlangıç Tarihi",
  "end_date": "Bitiş Tarihi",
  "pick_a_date": "Bir tarih seçiniz",
  "max_age": "Max. Yayın Tarihi",
  "published_date": "Yayın Tarihi",
  "pick_an_age": "Maksimum bir yayın tarihi seçiniz",
  "cancel": "İptal",
  "result": "Sonuç",
  "edit_search": "Aramayı Düzenle",
  "request_sent": "İstek Gönderildi",
  "est": "Ort.",
  "call": "Ara",
  "total": "Toplam",
  "distance": "Mesafe",
  "location": "Konum",
  "rating": "Değerlendirme",
  "start_time": "Alma Saati",
  "end_time": "Teslim Saati",
  "pick_a_time": "Bir saat seçiniz",
  "contact_phone": "İletişim Numarası",
  "enter_contact_phone": "Bir iletişim numarası giriniz",
  "end_date_must_be_after_than_first_date":
      "Bitiş tarihi başlangıç tarihi ile aynı gün veya sonrasında olmalıdır.",
  "pick_a_phone_number": "Bir iletişim numarası seçiniz",
  "add_new_phone_number": "Yeni numara ekle",
  "available": "Aktif",
  "search_places": "Arama yap",
  "my_profile": "Profilim",
  "contacts": "İletişim Hatları",
  "languages": "Diller",
  "theme": "Tema",
  "files": "Kayıtlı Belgeler",
  "delete_your_account": "Hesabını sil",
  "logout": "Çıkış yap",
  "edit_profile": "Profili Düzenle",
  "error_editing_user": "Profil düzenlenirken bir hata oluştu!.",
  "success_editing_user": "Profil başarıyla güncellendi!.",
  "camera": "Kamera",
  "gallery": "Galeri",
  "may_delete_after_login":
      "Yeniden giriş yaptıktan sonra hesabınızı silebilirsiniz.",
  "switch_language": "Dili Değiştir",
  "completed": "Tamamlandı",
  "canceled": "İptal Edildi",
  "you_need_a_profile": "Herhangi bir işlem için kayıt olmalısınız.",
  "cafe": "Kafe",
  "show_on_map": "Google'da Göster",
  "missing_values" : "Eksik bilgileri doldurunuz!",

};
const Map<String, String> en = {
    "want_to_sign_up" : "Hesap oluşturmak ister misin?",

  "success_adding_in_basket" : "Product added",

  "success_creating_order" : "Order created",
  "error_creating_order" : "Error creating order!",

  "no_product_found" : "No product found",

  "saved_cards" : "Saved Cards",
  "switch_theme" : "Switch Theme",

  "basket" : "Basket",

  "order" : "Order Now",
  "latte_description" : "A latte is a coffee beverage made with espresso and steamed milk. It is often topped with a small amount of foam.",
  "americano_description" : "An americano is a coffee beverage made by diluting espresso with hot water, giving it a similar strength to drip coffee but with a different flavor profile.",
  "mocha_description" : "A mocha is a chocolate-flavored latte. It is typically made with espresso, steamed milk, chocolate syrup, and whipped cream.",
  "espresso_description" : "Espresso is a concentrated form of coffee that is brewed by forcing hot water under high pressure through finely-ground coffee.",

  "welcome" : "Welcome",
  "most_popular" : "Most Popular",
  "all_products" : "All Products",

  "latte" : "Latte" ,
  "americano" : "Americano" ,
  "mocha" : "Mocha",
  "espresso" : "Espresso",
  "the_best_int_town" : "The best in town",
  "coffee" : "Coffee",
  "tea" : "Tea",
  "food" : "Food",
  "profile_view" : "Profile",
  "shop_view" : "Shop",
  "card_view" : "Card",
  "missing_values" : "There are missing values!",
  "show" : "View",
  "new_offer_load_body": "A new offer has been received for your load",
  "new_offer_truck_body": "A new offer has been received for your vehicle",
  "new_offer_load_title": "New offer for your load:",
  "new_offer_truck_title": "New offer for your vehicle:",
  "offer_accepted_load_title": "Offer accepted for your load:",
  "offer_accepted_truck_title": "Offer accepted for your vehicle:",
  "offer_accepted_body": "Your offer has been accepted.",
  "shipment_canceled_body": "Shipment has been canceled",
  "shipment_completed_body": "Shipment has been completed!",
  "new_message_title": "You have a message from",
  "show_on_map": "Show on Google",
  "gas_station": "Gas Station",
  "car_repair": "Auto Electrician",
  "cafe": "Cafe",
  "restaurant": "Restaurant",
  "hotel": "Hotel",
  "park": "Park & Rest Area",
  "anonymous_login": "Continue as Guest",
  "you_need_a_profile": "You must register to proceed.",
  "pick_load": "Select Load",
  "truck_post_details": "Vehicle Listing Details",
  "propose": "Offer",
  "update_shipment_state": "Update Shipment Status",
  "load_received": "Load Received",
  "target_reached": "Target Reached",
  "load_delivered": "Load Delivered",
  "load_owner": "Load Owner",
  "completed": "Completed",
  "canceled": "Canceled",
  "complete": "Finish",
  "this_shipment_is_canceled": "This shipment has been canceled!",
  "this_shipment_is_completed": "This shipment is completed.",
  "error_cancel_shipment": "An error occurred while canceling the shipment!",
  "success_cancel_shipment": "Shipment successfully canceled.",
  "error_complete_shipment": "An error occurred while completing the shipment!",
  "success_complete_shipment": "Shipment successfully completed.",
  "state": "State",
  "details": "Details",
  "start": "Shipment Started",
  "load": "Load",
  "oftruck": "With Vehicle",
  "shipment_details": "Shipment Details",
  "accepted": "Accepted",
  "active_shipments": "Active Shipments",
  "no_shipment_found": "No shipment found.",
  "success_creating_shipment": "Shipment successfully created.",
  "error_creating_shipment": "An error occurred while confirming the shipment!",
  "now": "Now",
  "offers": "Offers",
  "you_have_accepted_this_offer": "You have accepted this offer!",
  "you_have_rejected_this_offer": "You have rejected this offer!",
  "no_offer_found": "No offers found.",
  "chat": "Chat",
  "show_offers": "View Offers",
  "who_sent": "Offer Sender",
  "reject": "Reject",
  "success_accept_offer": "Offer accepted.",
  "error_accept_offer": "Offer could not be accepted. An unknown error occurred.",
  "success_reject_offer": "Offer rejected.",
  "error_reject_offer": "Offer could not be rejected. An unknown error occurred.",
  "delete_offer_content": "Deleting the selected offer will remove all its information.",
  "delete_offer_title": "Are you sure you want to delete the selected offer?",
  "offer_deleted_succesfully": "Offer successfully removed.",
  "error_creating_offer": "An error occurred while sending an offer!",
  "success_creating_offer": "Offer sent successfully",
  "offer_details": "Offer Details",
  "send_a_message": "Send a Message",
  "no_places_found": "No places found.",
  "loading": "Loading...",
  "chats": "Chats",
  "no_chats_found": "No chats found",
  "show_results": "Show Results",
  "hide_results": "Hide Results",
  "email": "Email",
  "phone": "Phone",
  "password": "Password",
  "password_again": "Repeat Password",
  "forgot_password": "Forgot Password",
  "login": "Login",
  "or": "or",
  "user_agreement": " User Agreement",
  "by_continuing": "By continuing",
  "accepted_user_agreement": "you accept the terms.",
  "sign_up": "Sign Up",
  "already_have_account": "Already have an account",
  "no_account": "Don't have an account",
  "add_photo": "Add Photo",
  "name": "Name",
  "surname": "Surname",
  "continue": "Continue",
  "pick_role": "Select a Role",
  "carrier": "Carrier",
  "shipper": "Shipper",
  "license_front": "Driver's License Front",
  "license_back": "Driver's License Back",
  "id_front": "ID Front",
  "id_back": "ID Back",
  "src": "Upload your SRC document",
  "psiko": "Upload your psychotechnic document",
  "confirm": "Confirm",
  "input_email": "Enter your email address.",
  "input_password": "Enter your password.",
  "input_password_again": "Re-enter your password.",
  "input_phone": "Enter your phone number.",
  "input_name": "Enter your name.",
  "input_surname": "Enter your surname.",
  "upload_necessary_files": "Upload Required Files",
  "fill_out": "Enter Your Information",
  "search": "Search",
  "discover": "Discover",
  "find_load": "Find Load",
  "find_loads": "Find Loads",
  "rest": "Rest",
  "fuel": "Find Fuel",
  "my_vehicles": "My Vehicles",
  "new_vehicle": "Add New Vehicle",
  "new_post_with_vehicle": "Add a new listing for a vehicle",
  "add_new_truck": "Add New Vehicle",
  "save": "Save",
  "length": "Length",
  "weight": "Weight",
  "price": "Price",
  "equipment_limits": "Load Limit",
  "full": "Full",
  "partial": "Partial",
  "truck_name": "Vehicle Name",
  "enter_truck_name": "Enter vehicle name.",
  "enter_trailer_name": "Enter trailer name.",
  "enter_description": "Enter a description",
  "description": "Description",
  "enter_truck_description": "Enter a description for the vehicle.",
  "truck_details": "Vehicle Details",
  "origin": "Origin",
  "target": "Target",
  "vehicle_type": "Vehicle Type",
  "start_date": "Start Date",
  "end_date": "End Date",
  "pick_a_date": "Select a date",
  "max_age": "Max. Publish Date",
  "published_date": "Publish Date",
  "pick_a_type": "Select Vehicle Type",
  "pick_an_age": "Select a maximum publish date",
  "cancel": "Cancel",
  "result": "Result",
  "edit_search": "Edit Search",
  "request_sent": "Request Sent",
  "est": "Est.",
  "load_details": "Load Details",
  "take_the_job": "Take the Job",
  "call": "Call",
  "total": "Total",
  "distance": "Distance",
  "vehicle_details": "Vehicle Details",
  "shipping_details": "Shipping Details",
  "rate_details": "Pricing Details",
  "company_details": "Company Details",
  "full_partial": "Full/Partial",
  "shipping_type": "Load Type",
  "pick_up_date": "Pickup Date",
  "dock_date": "Delivery Date",
  "reference": "Reference Code",
  "per_km": "Per KM",
  "company_name": "Company Name",
  "location": "Location",
  "rating": "Rating",
  "registration": "Upload your registration document",
  "i_am_a_broker": "I am a freight broker.\nI am not a load owner.",
  "i_am_a_carrier": "I am a freight carrier.\nI am not a load owner.",
  "i_am_a_shipper": "I am a load owner.",
  "my_loads": "My Loads",
  "new_post": "Create New Load",
  "start_time": "Pickup Time",
  "end_time": "Delivery Time",
  "pick_a_time": "Select a time",
  "contact_phone": "Contact Number",
  "enter_contact_phone": "Enter a contact number",
  "enter_price": "Enter a price",
  "post_your_car": "List Vehicle",
  "registered_city": "Registered City",
  "enter_registered_city": "Select the registered city of the vehicle",
  "bulk_or_palletized": "Is the load bulk or palletized?",
  "bulk": "Bulk",
  "palletized": "Palletized",
  "load_type": "Load Type",
  "post_new_load": "Create New Load",
  "load_volume": "Load Volume",
  "problem_signing_up": "An error occurred during registration!",
  "problem_creating_new_load": "An error occurred while adding a new load!",
  "new_load_created": "New load successfully listed.",
  "problem_creating_new_truck_post": "An error occurred while adding a new vehicle listing!",
  "new_truck_post_created": "New vehicle listing successfully created.",
  "success_creating_truck": "New vehicle successfully added.",
  "success_editing_truck": "Vehicle successfully updated.",
  "error_editing_truck": "An issue occurred while updating the vehicle!",
  "error_creating_truck": "An error occurred while adding a new vehicle!",
  "enter_weight": "Enter weight.",
  "enter_length": "Enter length.",
  "enter_volume": "Enter volume.",
  "volume": "Volume",
  "end_date_must_be_after_than_first_date": "End date must be the same or after the start date.",
  "bus": "Bus",
  "truck": "Truck",
  "car": "Car",
  "pick_a_phone_number": "Select a contact number",
  "add_new_phone_number": "Add new number",
  "available": "Active",
  "no_loads_found": "You have not added any load yet. You can create a new load.",
  "my_truck_has_trailer": "My vehicle has a trailer.",
  "trailer_details": "Trailer Details",
  "trailer_name": "Trailer Name",
  "trailer_tooltip": "Enter trailer information without including the vehicle total.",
  "pick_existing_trailers": "Select Existing Trailer",
  "search_places": "Search places",
  "delete_load_content": "Deleting the selected load will remove all its information.",
  "delete_truck_content": "Deleting the selected vehicle will remove all its information.",
  "delete_truck_post_content": "Deleting the selected vehicle listing will remove all its information.",
  "delete_load_title": "Are you sure you want to delete the selected load?",
  "delete_truck_title": "Are you sure you want to delete the selected vehicle?",
  "delete_truck_post_title": "Are you sure you want to delete the selected vehicle listing?",
  "load_deleted_succesfully": "Load successfully removed.",
  "truck_deleted_succesfully": "Vehicle successfully removed.",
  "truck_post_deleted_succesfully": "Vehicle listing successfully removed.",
  "edit_truck": "Edit Vehicle",
  "my_truck_posts": "My Vehicle Listings",
  "my_profile": "My Profile",
  "broker": "Freight Broker",
  "contacts": "Contact Lines",
  "languages": "Languages",
  "theme": "Theme",
  "files": "Saved Documents",
  "delete_your_account": "Delete Your Account",
  "logout": "Log Out",
  "edit_profile": "Edit Profile",
  "error_editing_user": "An error occurred while editing the profile!",
  "success_editing_user": "Profile successfully updated!",
  "camera": "Camera",
  "gallery": "Gallery",
  "may_delete_after_login": "You can delete your account after logging in again.",
  "switch_language": "Change Language",
  "go_home" : "Go Home",
};
